### ISSUE TITLE
BusyBox 1.23.1 (stable)

### ISSUE THREAD

**Issue by tianon** [jpetazzo/docker-busybox#13]
A new version of BusyBox was released today.  If you could update to it, that'd be swell.

Thanks! :wink:

**Comment by ewindisch** [comment]
Turns out this fixes a CVE, so we should get this applied!

ping @jpetazzo

**Comment by jpetazzo** [comment]
Will try to do this during downtime at SCALE next week. Thanks for the heads up

**Comment by dave-tucker** [comment]
@jpetazzo Buildroot 2015.02-rc1 has Busybox 1.23.1... 
I managed to get our image (which borrows heavily from this one) working with this over the weekend - https://github.com/socketplane/docker-busybox
