### ISSUE TITLE
busybox:uclibc (aka latest) only allows 3 DNS search paths

### ISSUE THREAD

**Issue by thockin** [jpetazzo/docker-busybox#19]
Not sure if this is the right place to file issues on busybox, but the hub page links here.

busybox:glibc works correctly, busybox:uclibc does not. :latest is currently tagged as :uclibc - it looks like this was updated today.

**Comment by thockin** [comment]
https://git.uclibc.org/uClibc/tree/include/resolv.h#n93

uclibc code shows support for 6

**Comment by tianon** [comment]
Doh, https://github.com/docker-library/busybox is the correct place, which I've fixed in https://github.com/docker-library/docs/commit/50f4da6ee98e71b93161b6880d44788312a6dc6d -- thanks for pointing that out too. :innocent:

**Comment by tianon** [comment]
So, we get uClibc via buildroot, IIRC (https://github.com/docker-library/busybox/blob/1cf3ff5b2bdf332e6ecff8c4aaaa94172f693332/uclibc/Dockerfile.builder), so it's probably best to see which version their `2015.11.1` release embeds (which I'm happy to get a bump PR for if we need a newer one).

**Comment by tianon** [comment]
Oh, that file hasn't changed in ages: https://git.uclibc.org/uClibc/log/include/resolv.h

Hmm.

**Comment by thockin** [comment]
we can take this to the "real" issues repo, I'll open a new issue

**Comment by tianon** [comment]
Awesome, thanks @thockin :+1:

Hopefully we can find the bottom of this. :disappointed:
