### ISSUE TITLE
ip addr segfault

### ISSUE THREAD

**Issue by porjo** [jpetazzo/docker-busybox#7]
```Shell
user@host ~ $ docker run --rm -i -t busybox:latest  /bin/sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
Segmentation fault
/ # 
```

Running on CoreOS 353, Docker 1.0

**Comment by tianon** [comment]
Any ideas @jpetazzo?

**Comment by apatrushev** [comment]
JFYI, I tried to build image with latest buildroot and behavior was the same

**Comment by jpetazzo** [comment]
No idea. I spent some time investigating this, but it's rather painful.
Someone with too much time on their hands might want to recompile to whole
stuff with debugging symbols, and also gdb, and give it a try. But I really
don't have time for that as of now, very unfortunately :'(

On Wed, Jan 28, 2015 at 2:41 AM, Anton Patrushev <notifications@github.com>
wrote:

> JFYI, I tried to build image with latest buildroot and behavior was the
> same
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpetazzo/docker-busybox/issues/7#issuecomment-71813711>
> .
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
"Is it safe to run applications into containers?"
http://www.slideshare.net/jpetazzo/docker-linux-containers-lxc-and-security

**Comment by estesp** [comment]
I've just created PR #14 which fixes the segfault and sets up IPv6 properly (as well as handles the problem around `nc` getting IPv6 addresses first).  Given Docker 1.5.0 is going to be out this week with proper IPv6 support, it probably makes sense to have the busybox image handle IPv6 appropriately.

**Comment by jpetazzo** [comment]
Thanks @estesp, major kudos for this!

I'm recompiling now and will push the updated tar shortly.

**Comment by jpetazzo** [comment]
Pushed! Thanks everybody. You all are awesome <3

The last step will be to update the library so that `docker pull busybox` gets us the right version.

**Comment by tpires** [comment]
Sorry to bring this up again but it still happens:

```
$ docker run -it --rm busybox /bin/sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
Segmentation fault (core dumped)
```

```
$ docker run -it --rm busybox:buildroot-2014.02 /bin/sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
Segmentation fault (core dumped)
```

It doesn't happen with 2013.08.1:

```
$ docker run -it --rm busybox:buildroot-2013.08.1 /bin/sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
30: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:11:00:0b brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.11/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:b/64 scope link tentative 
       valid_lft forever preferred_lft forever
```

**Comment by apatrushev** [comment]
@tpires AFAICS the commit hash in official library still not updated https://github.com/docker-library/official-images/blob/master/library/busybox. Probably you should yourself build the image  to get rid of this issue.

**Comment by LK4D4** [comment]
ping @tianon

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/687#issuecomment-97207904 and the following comments for what an updated image is currently stalled on.
